[[plugins]]
repo = 'skanehira/badapple.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neocomplete.vim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#auto_completion_start_length = 1

  let g:neocomplcache_enable_at_startup = 1
  let g:neocomplcache_enable_camel_case_completion = 1
  let g:neocomplcache_enable_underbar_completion = 1
  let g:neocomplcache_smart_case = 1
  let g:neocomplcache_min_syntax_length = 3
  let g:neocomplcache_manual_completion_start_length = 0
  let g:neocomplcache_caching_percent_in_statusline = 1
  let g:neocomplcache_enable_skip_completion = 1
  let g:neocomplcache_skip_input_time = '0.5'
'''

[[plugins]]
repo = 'Shougo/neoinclude.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
  let g:quickrun_config = {
  \  "_" : {
  \    "outputter/buffer/split" : ":botright 8sp",
  \    "outputter/buffer/close_on_empty" : 1,
  \    "outputter" : "quickfix"
  \  },
  \}
  au FileType qf nnoremap <silent><buffer>q :quit<CR>
'''

[[plugins]]
repo = 'Rican7/php-doc-modded'
on_ft = 'php'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'thinca/vim-ref'
hook_add = '''
  inoremap <silent><C-k> <C-o>:call<Space>ref#K('normal')<CR><ESC>
  nmap <silent>K <Plug>(ref-keyword)
  let g:ref_no_default_key_mappings = 1
  let g:ref_cache_dir        = $HOME . '/.vim/vim-ref/cache'
  let g:ref_detect_filetype     = {
  \  'php': 'phpmanual'
  \}
  let g:ref_phpmanual_path = $HOME . '/.vim/vim-ref/php-chunked-xhtml'
  let g:ref_use_cache   = 1
  let g:ref_use_vimproc  = 1
'''

[[plugins]]
repo = 'vim-scripts/taglist.vim'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'Valloric/MatchTagAlways'
hook_add = '''
  "オプション機能ONにする
  let g:mta_use_matchparen_group = 1
  "使用するファイルタイプ(phpを追加)
  let g:mta_filetypes = {
    \ 'html' : 1,
    \ 'xhtml' : 1,
    \ 'xml' : 1,
    \ 'jinja' : 1,
    \ 'php' : 1,
    \}
'''

[[plugins]]
repo = 'rking/ag.vim'

[[plugins]]
repo = 'phpactor/phpactor'
on_ft = 'php'
hook_add = '''
  nnoremap <Leader>p :call PhpDocSingle()<CR> 
  vnoremap <Leader>p :call PhpDocRange()<CR> 
'''

